### PR TITLE
Changing iclr image for H1edEyBKDS

### PR DESCRIPTION
**Pull request by mimosavvy**

### CODE REVIEW

**Comment by srush** [comment]
This image is amazing. But I gave you bad instructions. Can you also give us a small one < 50k for the small/ directory?

**Comment by mimosavvy** [comment]
Ah ok. Hmmm... would 300k be alright? I tried making a 50k one and you can't really see anything there. I can think of something creative if that has to be the restriction. Can you let me know?

**Comment by mimosavvy** [comment]
Ok I made a 200k and legible one. I can keep trying to reduce more.

**Comment by srush** [comment]
If you run `convert  in.png -quality 60 -resize 50% small/in.jpg` it should produce a good small one.

**Comment by mimosavvy** [comment]
Thanks. Is JPEG ok? I saw all other images are pngs and assumed you'd want that. I have a pretty good jpg now

**Comment by srush** [comment]
Yeah, the small directory is all jpegs.

**Pull request closed without merging**
